# Generated by Django 4.2.28 on 2026-03-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_delete_course_delete_mymodel_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
