# Generated by Django 4.2.28 on 2026-04-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='car_owned',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='car_type',
        ),
    ]
