# Generated by Django 4.2.28 on 2026-04-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0005_remove_profile_car_owned_remove_profile_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='car_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
