# Generated by Django 4.2.28 on 2026-05-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0006_profile_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='oil_change_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='tire_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='tire_warranty_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('Oil Change', 'Oil Change'), ('Tire Rotation', 'Tire Rotation'), ('Brake Service', 'Brake Service'), ('Battery Replacement', 'Battery Replacement'), ('Air Filter', 'Air Filter'), ('Coolant Flush', 'Coolant Flush'), ('Transmission Service', 'Transmission Service'), ('Other', 'Other')], max_length=100)),
                ('custom_type', models.CharField(blank=True, max_length=100)),
                ('service_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('mileage_at_service', models.PositiveIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='newApp.profile')),
            ],
        ),
    ]
