# Generated by Django 4.2.28 on 2026-05-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0007_profile_current_mileage_profile_oil_change_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vehicle_image_url',
            field=models.URLField(blank=True),
        ),
    ]
