# Generated by Django 4.2.28 on 2026-05-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0008_profile_vehicle_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tire_warranty_expiration',
        ),
    ]
