# Generated by Django 4.2.28 on 2026-05-12 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newApp', '0010_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_forum_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
