# Generated by Django 4.2.28 on 2026-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0012_forumreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
    ]
