# Generated by Django 4.2.28 on 2026-05-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0013_forumpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='oil_change_company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tire_company',
        ),
    ]
